---
- name: install docker compose
  package:
    name: docker-compose
    state: latest
  tags:
    - build_image
    - docker
- name: install docker
  package:
    name: docker
    state: latest
  tags:
    - build_image
    - docker
- name: 'docker dir, normally created upon startup'
  file:
    path: "/etc/docker"
    owner: root
    group: root
    mode: 774
    state: directory
  tags:
    - build_image
    - docker
- name: 'config docker daemon'
  copy:
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    content: |
      {
        "storage-driver": "overlay2",
        "log-driver": "journald",
        "graph": "/var/lib/containers"
      }
  tags:
    - build_image
    - docker

- name: enabel big daemon (for imaging)
  systemd:
    name: docker
    enabled: yes
  tags:
    - build_image
    - docker
- name: start big daemon
  systemd:
    name: docker
    state: started
  tags:
    - runtime
    - docker
    - deploy
